//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:24:20 PM CET 
//



import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HistoriaChoroby_QNAME = new QName("", "historia_choroby");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypHistoria }
     * 
     */
    public TypHistoria createTypHistoria() {
        return new TypHistoria();
    }

    /**
     * Create an instance of {@link TyphistoriaChoroby }
     * 
     */
    public TyphistoriaChoroby createTyphistoriaChoroby() {
        return new TyphistoriaChoroby();
    }

    /**
     * Create an instance of {@link TypPacjent }
     * 
     */
    public TypPacjent createTypPacjent() {
        return new TypPacjent();
    }

    /**
     * Create an instance of {@link TypUbezpieczenie }
     * 
     */
    public TypUbezpieczenie createTypUbezpieczenie() {
        return new TypUbezpieczenie();
    }

    /**
     * Create an instance of {@link TypNiezdolnoscPraca }
     * 
     */
    public TypNiezdolnoscPraca createTypNiezdolnoscPraca() {
        return new TypNiezdolnoscPraca();
    }

    /**
     * Create an instance of {@link TypTStatus }
     * 
     */
    public TypTStatus createTypTStatus() {
        return new TypTStatus();
    }

    /**
     * Create an instance of {@link TypKrew }
     * 
     */
    public TypKrew createTypKrew() {
        return new TypKrew();
    }

    /**
     * Create an instance of {@link TypHistoria.Choroba }
     * 
     */
    public TypHistoria.Choroba createTypHistoriaChoroba() {
        return new TypHistoria.Choroba();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TyphistoriaChoroby }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "historia_choroby")
    public JAXBElement<TyphistoriaChoroby> createHistoriaChoroby(TyphistoriaChoroby value) {
        return new JAXBElement<TyphistoriaChoroby>(_HistoriaChoroby_QNAME, TyphistoriaChoroby.class, null, value);
    }

}
