//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:24:20 PM CET 
//



import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for typHistoria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typHistoria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="choroba" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="wywiad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="numer_choroby" type="{}typNumer_choroby"/>
 *                   &lt;element name="pierwsze_zachorowanie" type="{}typTN"/>
 *                   &lt;element name="niezdolnosc_praca" type="{}typNiezdolnosc_praca"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typHistoria", propOrder = {
    "choroba"
})
public class TypHistoria {

    protected List<TypHistoria.Choroba> choroba;

    /**
     * Gets the value of the choroba property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the choroba property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChoroba().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypHistoria.Choroba }
     * 
     * 
     */
    public List<TypHistoria.Choroba> getChoroba() {
        if (choroba == null) {
            choroba = new ArrayList<TypHistoria.Choroba>();
        }
        return this.choroba;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="wywiad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="numer_choroby" type="{}typNumer_choroby"/>
     *         &lt;element name="pierwsze_zachorowanie" type="{}typTN"/>
     *         &lt;element name="niezdolnosc_praca" type="{}typNiezdolnosc_praca"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "wywiad",
        "numerChoroby",
        "pierwszeZachorowanie",
        "niezdolnoscPraca"
    })
    public static class Choroba {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar data;
        @XmlElement(required = true)
        protected String wywiad;
        @XmlElement(name = "numer_choroby", required = true)
        protected String numerChoroby;
        @XmlElement(name = "pierwsze_zachorowanie", required = true)
        protected String pierwszeZachorowanie;
        @XmlElement(name = "niezdolnosc_praca", required = true)
        protected TypNiezdolnoscPraca niezdolnoscPraca;

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setData(XMLGregorianCalendar value) {
            this.data = value;
        }

        /**
         * Gets the value of the wywiad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWywiad() {
            return wywiad;
        }

        /**
         * Sets the value of the wywiad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWywiad(String value) {
            this.wywiad = value;
        }

        /**
         * Gets the value of the numerChoroby property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumerChoroby() {
            return numerChoroby;
        }

        /**
         * Sets the value of the numerChoroby property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumerChoroby(String value) {
            this.numerChoroby = value;
        }

        /**
         * Gets the value of the pierwszeZachorowanie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPierwszeZachorowanie() {
            return pierwszeZachorowanie;
        }

        /**
         * Sets the value of the pierwszeZachorowanie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPierwszeZachorowanie(String value) {
            this.pierwszeZachorowanie = value;
        }

        /**
         * Gets the value of the niezdolnoscPraca property.
         * 
         * @return
         *     possible object is
         *     {@link TypNiezdolnoscPraca }
         *     
         */
        public TypNiezdolnoscPraca getNiezdolnoscPraca() {
            return niezdolnoscPraca;
        }

        /**
         * Sets the value of the niezdolnoscPraca property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypNiezdolnoscPraca }
         *     
         */
        public void setNiezdolnoscPraca(TypNiezdolnoscPraca value) {
            this.niezdolnoscPraca = value;
        }

    }

}
